version: "3"

services:
  shopware:
    # use either tag "latest" or any other version like "6.1.5", ...
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "8080:80"
      - "3333:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
      - "./src/custom/plugins/AiDescription:/var/www/html/custom/plugins/AiDescription"
      - "/var/www/html/custom/plugins/AiDescription/.git/"
      - "/var/www/html/custom/plugins/AiDescription/vendor/"
      - "/var/www/html/custom/plugins/AiDescription/src/Resources/app/administration/node_modules/"
      - "/var/www/html/custom/plugins/AiDescription/src/Resources/app/storefront/node_modules/"
      - "/var/www/html/custom/plugins/AiDescription/tests/Cypress/"
      - "/var/www/html/.git/"
      - "/var/www/html/public/build"
      - "/var/www/html/var/cache"
      - "/var/www/html/vendor"
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      # default = latest PHP, optional = specific version
      - PHP_VERSION=8.1

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
