version: "3"

services:
  shopware:
    # use either tag "latest" or any other version like "6.1.5", ...
    image: dockware/dev:latest
    container_name: shopware-test-store
    ports:
      - "8080:80"
      - "3333:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "db_volume_shopware:/var/lib/mysql"
      - "shop_volume_shopware:/var/www/html"
      - "./shopware-plugin/AiDescription:/var/www/html/custom/plugins/AiDescription"
      - "./shopware-example-store-test-data/example-store.dump:/var/www/html/mysqldata/example-store.dump"
      - "/var/www/html/custom/plugins/AiDescription/.git/"
      - "/var/www/html/custom/plugins/AiDescription/vendor/"
      - "/var/www/html/custom/plugins/AiDescription/src/Resources/app/administration/node_modules/"
      - "/var/www/html/custom/plugins/AiDescription/src/Resources/app/storefront/node_modules/"
      - "/var/www/html/custom/plugins/AiDescription/tests/Cypress/"
      - "/var/www/html/.git/"
      - "/var/www/html/public/build"
      - "/var/www/html/var/cache"
      - "/var/www/html/vendor"
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      - XDEBUG_CONFIG=idekey=vsc
      # default = latest PHP, optional = specific version
      - PHP_VERSION=8.2
    command: bash -c "cd /var/www && make watch-admin"


volumes:
  db_volume_shopware:
    driver: local

  shop_volume_shopware:
    driver: local

networks:
  web:
    external: false
